import 'package:equatable/equatable.dart';

class FarmEntity extends Equatable { const FarmEntity({required this.id, required this.name, required this.owner, required this.city, required this.state}); final String id; final String name; final String owner; final String city; final String state; @override List<Object?> get props => [id,name,owner,city,state]; }
class FieldEntity extends Equatable { const FieldEntity({required this.id, required this.name, required this.farmId}); final String id; final String name; final String farmId; @override List<Object?> get props => [id,name,farmId]; }
class CropEntity extends Equatable { const CropEntity({required this.id, required this.name, required this.category}); final String id; final String name; final String category; @override List<Object?> get props => [id,name,category]; }
class SeasonEntity extends Equatable { const SeasonEntity({required this.id, required this.name, required this.year}); final String id; final String name; final int year; @override List<Object?> get props => [id,name,year]; }
class OperationEntity extends Equatable { const OperationEntity({required this.id, required this.type, required this.description}); final String id; final String type; final String description; @override List<Object?> get props => [id,type,description]; }
class MachineEntity extends Equatable { const MachineEntity({required this.id, required this.name, required this.type}); final String id; final String name; final String type; @override List<Object?> get props => [id,name,type]; }
class MachineRecordEntity extends Equatable { const MachineRecordEntity({required this.id, required this.machineId, required this.recordType}); final String id; final String machineId; final String recordType; @override List<Object?> get props => [id,machineId,recordType]; }
class FinancialEntryEntity extends Equatable { const FinancialEntryEntity({required this.id, required this.type, required this.description, required this.value}); final String id; final String type; final String description; final double value; @override List<Object?> get props => [id,type,description,value]; }
class AiResultEntity extends Equatable { const AiResultEntity({required this.score, required this.recommendations}); final double score; final List<String> recommendations; @override List<Object?> get props => [score,recommendations]; }
class SatelliteImageEntity extends Equatable { const SatelliteImageEntity({required this.id, required this.provider, required this.ndviAverage, required this.thumbnailUrl}); final String id; final String provider; final double ndviAverage; final String thumbnailUrl; @override List<Object?> get props => [id,provider,ndviAverage,thumbnailUrl]; }
